- name: install haproxy
  hosts: "proxmox_jumphost"
  #remote_user: 'root'
  become: true
  vars:
    - file_conf: "jump_proxmox_haproxy.cfg.j2" 

  tasks:

    - name: install haproxy
      package: 
        name: haproxy
        state: present
      #notify:
      # - restart haproxy


    - name: copy configuration file
      template: 
        src: "{{file_conf}}"
        dest: /etc/haproxy/haproxy.cfg
      notify: 
        - restart haproxy

  handlers:

    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
        enabled: true
    