- name: install named
  hosts: "common"
  remote_user: 'root'

  tasks:

    - name: install named
      package: 
        name: bind
        state: present
      notify: 
        - restart named
    
    - name: copy zone dns 
      template:
        src: templates/named.conf.j2
        dest: /etc/named.conf
      notify: restart named
    
    - name: copy entry dns 
      template:
        src: templates/named.devops.lab.j2
        dest: /var/named/named.devops.lab
      notify: restart named

    - name: copy entry dns 
      template:
        src: templates/ocp.lan.reverse.j2
        dest: /var/named/ocp.lan.reverse
      notify: restart named
    
  handlers:

   - name: restart named
     service:
      name: named
      state: restarted
      enabled: true
